# Importing libraries

In [ ]:
import numpy as np
import pandas as pd
from google.colab import files

# Uploading dataset in the form of csv

In [ ]:
upload=files.upload()
upload

Saving Admission1.csv to Admission1.csv


{'Admission1.csv': b'admit,gre,gpa,ses,Gender_Male,Race,rank\r\n0,380,3.61,1,0,3,3\r\n1,660,3.67,2,0,2,3\r\n1,800,4,2,0,2,1\r\n1,640,3.19,1,1,2,4\r\n0,520,2.93,3,1,2,4\r\n1,760,3,2,1,1,2\r\n1,560,2.98,2,1,2,1\r\n0,400,3.08,2,0,2,2\r\n1,540,3.39,1,1,1,3\r\n0,700,3.92,1,0,2,2\r\n0,800,4,1,1,1,4\r\n0,440,3.22,3,0,2,1\r\n1,760,4,3,1,2,1\r\n0,700,3.08,2,0,2,2\r\n1,700,4,2,1,1,1\r\n0,480,3.44,3,0,1,3\r\n0,780,3.87,2,0,3,4\r\n0,360,2.56,3,1,3,3\r\n0,800,3.75,1,1,3,2\r\n1,540,3.81,1,0,3,1\r\n0,500,3.17,3,0,2,3\r\n1,660,3.63,1,0,1,2\r\n0,600,2.82,1,0,3,4\r\n0,680,3.19,1,0,1,4\r\n1,760,3.35,2,0,2,2\r\n1,800,3.66,2,1,1,1\r\n1,620,3.61,2,0,1,1\r\n1,520,3.74,2,0,3,4\r\n1,780,3.22,1,0,1,2\r\n0,520,3.29,1,0,1,1\r\n0,540,3.78,1,1,1,4\r\n0,760,3.35,2,1,1,3\r\n0,600,3.4,3,0,1,3\r\n1,800,4,3,0,1,3\r\n0,360,3.14,1,1,2,1\r\n0,400,3.05,3,0,2,2\r\n0,580,3.25,1,0,2,1\r\n0,520,2.9,2,0,2,3\r\n1,500,3.13,2,0,2,2\r\n1,520,2.68,2,0,1,3\r\n0,560,2.42,1,1,3,2\r\n1,580,3.32,1,0,1,2\r\n1,600,3.15,2,1,1,2\r\n0,500,3.31

In [ ]:
import io

In [ ]:
df=pd.read_csv(io.BytesIO(upload['Admission1.csv']))

In [ ]:
df.head(5)

admit  gre   gpa  ses  Gender_Male  Race  rank
0      0  380  3.61    1            0     3     3
1      1  660  3.67    2            0     2     3
2      1  800  4.00    2            0     2     1
3      1  640  3.19    1            1     2     4
4      0  520  2.93    3            1     2     4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   admit        400 non-null    int64  
 1   gre          400 non-null    int64  
 2   gpa          400 non-null    float64
 3   ses          400 non-null    int64  
 4   Gender_Male  400 non-null    int64  
 5   Race         400 non-null    int64  
 6   rank         400 non-null    int64  
dtypes: float64(1), int64(6)
memory usage: 22.0 KB


In [ ]:
df.isnull().sum()

admit          0
gre            0
gpa            0
ses            0
Gender_Male    0
Race           0
rank           0
dtype: int64

# Fill null values with mean

In [36]:
for values in df:
  df[values].fillna((df[values].mean()),inplace=True)

# Assigning x and y values

In [37]:
x=df[:]


In [38]:
x.drop('admit',axis=1,inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [39]:
y=df['admit']

# Applying preprocessing

In [40]:
from sklearn import preprocessing

In [41]:
minmaxscaler=preprocessing.MinMaxScaler()

In [42]:
x=minmaxscaler.fit_transform(x)
x

array([[0.27586207, 0.77586207, 0.        , 0.        , 1.        ,
        0.66666667],
       [0.75862069, 0.81034483, 0.5       , 0.        , 0.5       ,
        0.66666667],
       [1.        , 1.        , 0.5       , 0.        , 0.5       ,
        0.        ],
       ...,
       [0.4137931 , 0.21264368, 1.        , 0.        , 0.5       ,
        0.33333333],
       [0.82758621, 0.79885057, 0.        , 1.        , 0.        ,
        0.33333333],
       [0.65517241, 0.93678161, 0.5       , 1.        , 1.        ,
        0.66666667]])

# Training and spliting

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

# Fitting Regression Algorithm

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
lr=LogisticRegression()

In [47]:
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
y_pred=lr.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

# Checking accuracy

In [49]:
from sklearn import metrics

In [50]:
metrics.accuracy_score(y_test,y_pred)

0.725

# Fitting classification

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
rf=RandomForestClassifier()

In [53]:
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [54]:
y_pred1=rf.predict(x_test)
y_pred1

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1])

# Checking accuracy

In [55]:
metrics.accuracy_score(y_test,y_pred1)

0.7166666666666667